# Generated by Django 4.2.7 on 2026-03-09 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobseekerapp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('qualification', models.CharField(max_length=120)),
                ('hobbies', models.TextField()),
                ('skills', models.TextField()),
                ('address', models.TextField()),
                ('profile_photo', models.ImageField(upload_to='profile_photos/')),
            ],
        ),
    ]
