# Generated by Django 4.2.7 on 2026-03-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerapp',
            name='profile_photo',
            field=models.ImageField(upload_to='profile_photo/'),
        ),
    ]
