# Generated by Django 6.0 on 2026-04-06 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseekerapp', '0002_alter_jobseekerapp_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseekerapp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
