# Generated by Django 4.2.7 on 2026-03-04 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='useraccount',
            fields=[
                ('firstname', models.CharField(max_length=120)),
                ('lastname', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.CharField(max_length=10)),
                ('role', models.CharField(choices=[{'Employer', 'employer'}, {'Job Seeker', 'jobseeker'}], max_length=10)),
            ],
        ),
    ]
