# Generated by Django 4.2.7 on 2026-03-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useraccount',
        ),
    ]
