# Generated by Django 4.2.7 on 2026-03-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerdetails',
            old_name='emplocation',
            new_name='emploc',
        ),
    ]
